issuesOpened: >
  Thanks for opening a new issue. This repository contains an archive of the Electron-based Wavebox Classic, which was superseded by Wavebox 10 in 2019.
  
  If you need help, support or want to report a bug with Wavebox 10, please contact support directly, either using the in-app support button in the sidebar or the online support form at https://wavebox.io/support
  
